### PR TITLE
Update

### PR DESCRIPTION
**Pull request by nullified33**

### CODE REVIEW

**Comment by machinesmith42** [comment]
iris does not support immersive portals so far so does this work?

**Comment by nullified33** [comment]
> iris does not support immersive portals so far so does this work?

i think it might

**Comment by nullified33** [comment]
i

> > iris does not support immersive portals so far so does this work?
> 
> i think it might

but so far it is not able to be compiled

**Comment by nullified33** [comment]
The best way i think this could be done is by merging the iris jar and the immersive portals jar

**Comment by nullified33** [comment]
This is all entirely experimental

**Comment by nullified33** [comment]
Log errors:
https://github.com/3prm3/sodium-fabric/runs/2326646211?check_suite_focus=true
https://github.com/3prm3/sodium-fabric/runs/2326646204?check_suite_focus=true
https://github.com/3prm3/sodium-fabric/runs/2326648558?check_suite_focus=true
https://github.com/3prm3/sodium-fabric/runs/2326648569?check_suite_focus=true
https://github.com/3prm3/sodium-fabric/runs/2326648565?check_suite_focus=true
https://github.com/3prm3/sodium-fabric/runs/2326646210?check_suite_focus=true

**Comment by machinesmith42** [comment]
has this been fixed? https://github.com/IrisShaders/Iris/issues/190

**Comment by nullified33** [comment]
> has this been fixed? [IrisShaders/Iris#190](https://github.com/IrisShaders/Iris/issues/190)

apparently not

**Comment by nullified33** [comment]
> > has this been fixed? [IrisShaders/Iris#190](https://github.com/IrisShaders/Iris/issues/190)
> 
> apparently not

**Comment by nullified33** [comment]
> has this been fixed? [IrisShaders/Iris#190](https://github.com/IrisShaders/Iris/issues/190)

l hope this is fixed

**Comment by machinesmith42** [comment]
i mean i can try building it but this might be pointless

**Comment by machinesmith42** [comment]
and it broke
https://github.com/machinesmith42/sodium-fabric/runs/2327511235?check_suite_focus=true

**Comment by nullified33** [comment]
> and it broke
> https://github.com/machinesmith42/sodium-fabric/runs/2327511235?check_suite_focus=true

k

**Comment by machinesmith42** [comment]
closing until iris support is achieved

**Pull request merged**
